export const data = JSON.parse("{\"key\":\"v-3450ec4c\",\"path\":\"/zh/javascript/microServer.html\",\"title\":\"前端微服务\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"前端微服务\",\"shortTitle\":\"前端微服务\",\"icon\":\"page\",\"order\":1,\"author\":\"WY\",\"date\":\"2023-03-29T00:00:00.000Z\",\"category\":[\"micro\",\"single-spa\",\"systemJs\",\"乾坤(qiankun)\",\"无界(ESM)\",\"MicroApp\",\"模块联邦\"],\"tag\":[\"micro\",\"single-spa\",\"systemJs\",\"乾坤(qiankun)\",\"无界(ESM)\",\"MicroApp\",\"模块联邦\"],\"sticky\":true,\"star\":true,\"footer\":\"Footer content for test\",\"copyright\":\"No Copyright\",\"description\":\"SystemJs single-spa ::: code-tabs#shell tab ESM(无界) tab 乾坤(qiankun) tab microApp :::\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://wangyongtest.github.io/frontendtechnologysharing.github.com/zh/javascript/microServer.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"前端微服务\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"SystemJs single-spa ::: code-tabs#shell tab ESM(无界) tab 乾坤(qiankun) tab microApp :::\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"WY\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"micro\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"single-spa\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"systemJs\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"乾坤(qiankun)\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"无界(ESM)\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"MicroApp\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"模块联邦\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-03-29T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"前端微服务\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-03-29T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"WY\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"SystemJs\",\"slug\":\"systemjs\",\"link\":\"#systemjs\",\"children\":[]},{\"level\":2,\"title\":\"single-spa\",\"slug\":\"single-spa\",\"link\":\"#single-spa\",\"children\":[]}],\"readingTime\":{\"minutes\":0.47,\"words\":142},\"filePathRelative\":\"zh/javascript/microServer.md\",\"localizedDate\":\"2023年3月29日\",\"excerpt\":\"\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
