export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"e":"<h1> Intro Page</h1>\n<p>Place your introduction and profile here.</p>\n","y":"a","t":"Intro Page","i":"info"},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"e":"<!-- markdownlint-disable MD024 MD033 MD051 -->\n","y":"s","t":"Slide page","i":"slides"},["/slides","/slides.md"]],
  ["v-858cfdd6","/zh/intro.html",{"e":"<h1> 介绍页</h1>\n<p>将你的个人介绍和档案放置在此处。</p>\n","y":"a","t":"介绍页","i":"info"},["/zh/intro","/zh/intro.md"]],
  ["v-2d0ad528","/zh/",{"y":"h","t":""},["/zh/index.html","/zh/README.md"]],
  ["v-269ae70f","/zh/slides.html",{"e":"<!-- markdownlint-disable MD024 MD033 MD051 -->\n","y":"s","t":"幻灯片页","i":"slides"},["/zh/slides","/zh/slides.md"]],
  ["v-6129d94a","/en/vue/reactive.html",{"a":"WY","d":"2023-03-08T00:00:00.000Z","l":"March 8, 2023","c":["Vue"],"g":["Vue"],"u":true,"y":"a","t":"Reactive","i":"page","O":1,"s":"Reactive"},["/en/vue/reactive","/en/vue/reactive.md"]],
  ["v-26f4361c","/en/vue/ref.html",{"a":"WY","d":"2023-03-08T00:00:00.000Z","l":"March 8, 2023","c":["Vue"],"g":["Vue"],"u":true,"y":"a","t":"Ref","i":"page","O":1,"s":"Ref"},["/en/vue/ref","/en/vue/ref.md"]],
  ["v-e11bb6e2","/zh/vue/reactive.html",{"a":"WY","d":"2023-03-08T00:00:00.000Z","l":"2023年3月8日","c":["Vue"],"g":["Vue"],"u":true,"y":"a","t":"Reactive","i":"page","O":1,"s":"Reactive"},["/zh/vue/reactive","/zh/vue/reactive.md"]],
  ["v-3ac133b7","/zh/vue/ref.html",{"a":"WY","d":"2023-03-08T00:00:00.000Z","l":"2023年3月8日","c":["Vue"],"g":["Vue"],"u":true,"e":"<!-- 加上这个注释more仅显示标题 -->\n","y":"a","t":"Ref","i":"page","O":1},["/zh/vue/ref","/zh/vue/ref.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
  ["v-075d9ff6","/en/vue/",{"y":"p","t":"Vue"},["/en/vue/index.html"]],
  ["v-2d0a870d","/en/",{"y":"p","t":"En"},["/en/index.html"]],
  ["v-54036891","/zh/vue/",{"y":"p","t":"Vue"},["/zh/vue/index.html"]],
  ["v-5bc93818","/category/",{"y":"p","t":"Category","I":0},["/category/index.html"]],
  ["v-744d024e","/tag/",{"y":"p","t":"Tag","I":0},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"y":"p","t":"Articles","I":0},["/article/index.html"]],
  ["v-154dc4c4","/star/",{"y":"p","t":"Star","I":0},["/star/index.html"]],
  ["v-01560935","/timeline/",{"y":"p","t":"Timeline","I":0},["/timeline/index.html"]],
  ["v-65f6d381","/category/vue/",{"y":"p","t":"Vue Category","I":0},["/category/vue/index.html"]],
  ["v-26f8293d","/tag/page-config/",{"y":"p","t":"Page config Tag","I":0},["/tag/page-config/index.html"]],
  ["v-54d7ff21","/zh/article/",{"y":"p","t":"文章","I":0},["/zh/article/index.html"]],
  ["v-2c3ee7f5","/zh/star/",{"y":"p","t":"收藏","I":0},["/zh/star/index.html"]],
  ["v-27b02be6","/zh/timeline/",{"y":"p","t":"时间轴","I":0},["/zh/timeline/index.html"]],
  ["v-ac0c2a6a","/category/guide/",{"y":"p","t":"Guide Category","I":0},["/category/guide/index.html"]],
  ["v-b302da92","/tag/vue/",{"y":"p","t":"Vue Tag","I":0},["/tag/vue/index.html"]],
  ["v-fbb94a6e","/zh/category/",{"y":"p","t":"分类","I":0},["/zh/category/index.html"]],
  ["v-8fa3949c","/zh/category/vue/",{"y":"p","t":"Vue 分类","I":0},["/zh/category/vue/index.html"]],
  ["v-30e296fe","/tag/guide/",{"y":"p","t":"Guide Tag","I":0},["/tag/guide/index.html"]],
  ["v-4be184bc","/zh/category/guide/",{"y":"p","t":"Guide 分类","I":0},["/zh/category/guide/index.html"]],
  ["v-540234fd","/zh/tag/",{"y":"p","t":"标签","I":0},["/zh/tag/index.html"]],
  ["v-7bf86528","/zh/tag/page-config/",{"y":"p","t":"Page config 标签","I":0},["/zh/tag/page-config/index.html"]],
  ["v-6decd5e6","/zh/tag/vue/",{"y":"p","t":"Vue 标签","I":0},["/zh/tag/vue/index.html"]],
  ["v-e70e3020","/zh/tag/guide/",{"y":"p","t":"Guide 标签","I":0},["/zh/tag/guide/index.html"]],
]
