export const pagesRoutes = [
  ["v-184f4da6","/intro.html",{"e":"<h1> Intro Page</h1>\n<p>Place your introduction and profile here.</p>\n","y":"a","t":"Intro Page","i":"info"},["/intro","/intro.md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"e":"<!-- markdownlint-disable MD024 MD033 MD051 -->\n","y":"s","t":"Slide page","i":"slides"},["/slides","/slides.md"]],
  ["v-858cfdd6","/zh/intro.html",{"e":"<h1> 介绍页</h1>\n<p>将你的个人介绍和档案放置在此处。</p>\n","y":"a","t":"介绍页","i":"info"},["/zh/intro","/zh/intro.md"]],
  ["v-2d0ad528","/zh/",{"y":"h","t":""},["/zh/index.html","/zh/README.md"]],
  ["v-269ae70f","/zh/slides.html",{"e":"<!-- markdownlint-disable MD024 MD033 MD051 -->\n","y":"s","t":"幻灯片页","i":"slides"},["/zh/slides","/zh/slides.md"]],
  ["v-971c3fc0","/en/javascript/proxy.html",{"a":"WY","d":"2023-03-08T00:00:00.000Z","l":"March 8, 2023","c":["Vue"],"g":["Vue"],"u":true,"y":"a","t":"Proxy","i":"page","O":1,"s":"Proxy"},["/en/javascript/proxy","/en/javascript/proxy.md"]],
  ["v-6129d94a","/en/vue/reactive.html",{"a":"WY","d":"2023-03-08T00:00:00.000Z","l":"March 8, 2023","c":["Vue"],"g":["Vue"],"u":true,"y":"a","t":"Reactive","i":"page","O":1,"s":"Reactive"},["/en/vue/reactive","/en/vue/reactive.md"]],
  ["v-26f4361c","/en/vue/ref.html",{"a":"WY","d":"2023-03-08T00:00:00.000Z","l":"March 8, 2023","c":["Vue"],"g":["Vue"],"u":true,"y":"a","t":"Ref","i":"page","O":1,"s":"Ref"},["/en/vue/ref","/en/vue/ref.md"]],
  ["v-1205b4f4","/zh/javascript/PDF-Preview.html",{"a":"WY","d":"2023-03-09T00:00:00.000Z","l":"2023年3月9日","c":["javascript","PDFPreview"],"g":["javascript","PDFPreview"],"u":true,"y":"a","t":"PDF-Preview","i":"page","O":1,"s":"PDF-Preview"},["/zh/javascript/PDF-Preview","/zh/javascript/PDF-Preview.md"]],
  ["v-b92dfe36","/zh/javascript/proxy.html",{"a":"WY","d":"2023-03-08T00:00:00.000Z","l":"2023年3月8日","c":["javascript","Proxy"],"g":["Proxy","javascript"],"u":true,"y":"a","t":"Proxy","i":"page","O":1,"s":"Proxy"},["/zh/javascript/proxy","/zh/javascript/proxy.md"]],
  ["v-3f3e6852","/zh/javascript/watcher.html",{"a":"WY","d":"2023-03-08T00:00:00.000Z","l":"2023年3月8日","c":["javascript","设计模式"],"g":["javascript","设计模式"],"u":true,"y":"a","t":"观察者和发布订阅模式","i":"page","O":1,"s":"Proxy"},["/zh/javascript/watcher","/zh/javascript/watcher.md"]],
  ["v-20c378fa","/zh/nodejs/download-git-repo.html",{"a":"WY","d":"2023-03-16T00:00:00.000Z","l":"2023年3月16日","c":["nodejs","npm"],"g":["nodejs","-npm"],"u":true,"y":"a","t":"download-git-repo","i":"page","O":1,"s":"download-git-repo"},["/zh/nodejs/download-git-repo","/zh/nodejs/download-git-repo.md"]],
  ["v-0352acb8","/zh/vue/devStandard.html",{"a":"WY","d":"2023-03-08T00:00:00.000Z","l":"2023年3月8日","c":["Vue","Standard"],"g":["Vue","Standard"],"u":true,"y":"a","t":"开发规范-Vue","i":"page","O":1,"s":"开发规范"},["/zh/vue/devStandard","/zh/vue/devStandard.md"]],
  ["v-e11bb6e2","/zh/vue/reactive.html",{"e":"<!--\n * @Author: wy wang.yong@easttrans.cn\n * @Date: 2023-03-09 18:02:44\n * @LastEditors: wy wang.yong@easttrans.cn\n * @LastEditTime: 2023-03-20 14:03:52\n * @FilePath: \\frontendtechnologysharing.github.com\\src\\zh\\vue\\reactive.md\n * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE\n-->\n<hr>\n<h1> This is the title of the article</h1>\n<p>title: Reactive\nshortTitle: Reactive</p>\n<h1> This is the icon of the page</h1>\n<p>icon: page</p>\n<h1> This control sidebar order</h1>\n<p>order: 1</p>\n<h1> Set author</h1>\n<p>author: WY</p>\n<h1> Set writing time</h1>\n<p>date: 2023-03-08</p>\n<h1> A page can have multiple categories</h1>\n<p>category:</p>\n<ul>\n<li>Vue</li>\n</ul>\n<h1> A page can have multiple tags</h1>\n<p>tag:</p>\n<ul>\n<li>Vue</li>\n</ul>\n<h1> this page is sticky in article list</h1>\n<p>sticky: true</p>\n<h1> this page will appear in starred articles</h1>\n<p>star: true</p>\n<h1> You can customize footer content</h1>\n<p>footer: Footer content for test</p>\n<h1> You can customize copyright content</h1>\n<h2> copyright: No Copyright</h2>\n","y":"a","t":"This is the title of the article"},["/zh/vue/reactive","/zh/vue/reactive.md"]],
  ["v-3ac133b7","/zh/vue/ref.html",{"a":"WY","d":"2023-03-08T00:00:00.000Z","l":"2023年3月8日","c":["Vue"],"g":["Vue"],"u":true,"y":"a","t":"Ref","i":"page","O":1},["/zh/vue/ref","/zh/vue/ref.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
  ["v-cfb05996","/en/javascript/",{"y":"p","t":"Javascript"},["/en/javascript/index.html"]],
  ["v-2d0a870d","/en/",{"y":"p","t":"En"},["/en/index.html"]],
  ["v-075d9ff6","/en/vue/",{"y":"p","t":"Vue"},["/en/vue/index.html"]],
  ["v-ef71938c","/zh/javascript/",{"y":"p","t":"Javascript"},["/zh/javascript/index.html"]],
  ["v-0742a49c","/zh/nodejs/",{"y":"p","t":"Nodejs"},["/zh/nodejs/index.html"]],
  ["v-54036891","/zh/vue/",{"y":"p","t":"Vue"},["/zh/vue/index.html"]],
  ["v-5bc93818","/category/",{"y":"p","t":"Category","I":0},["/category/index.html"]],
  ["v-744d024e","/tag/",{"y":"p","t":"Tag","I":0},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"y":"p","t":"Articles","I":0},["/article/index.html"]],
  ["v-154dc4c4","/star/",{"y":"p","t":"Star","I":0},["/star/index.html"]],
  ["v-01560935","/timeline/",{"y":"p","t":"Timeline","I":0},["/timeline/index.html"]],
  ["v-65f6d381","/category/vue/",{"y":"p","t":"Vue Category","I":0},["/category/vue/index.html"]],
  ["v-b302da92","/tag/vue/",{"y":"p","t":"Vue Tag","I":0},["/tag/vue/index.html"]],
  ["v-54d7ff21","/zh/article/",{"y":"p","t":"文章","I":0},["/zh/article/index.html"]],
  ["v-2c3ee7f5","/zh/star/",{"y":"p","t":"收藏","I":0},["/zh/star/index.html"]],
  ["v-27b02be6","/zh/timeline/",{"y":"p","t":"时间轴","I":0},["/zh/timeline/index.html"]],
  ["v-fbb94a6e","/zh/category/",{"y":"p","t":"分类","I":0},["/zh/category/index.html"]],
  ["v-540234fd","/zh/tag/",{"y":"p","t":"标签","I":0},["/zh/tag/index.html"]],
  ["v-945adc0e","/zh/category/javascript/",{"y":"p","t":"javascript 分类","I":0},["/zh/category/javascript/index.html"]],
  ["v-f7c5e176","/zh/tag/javascript/",{"y":"p","t":"javascript 标签","I":0},["/zh/tag/javascript/index.html"]],
  ["v-9e9d1c20","/zh/category/pdfpreview/",{"y":"p","t":"PDFPreview 分类","I":0},["/zh/category/pdfpreview/index.html"]],
  ["v-7efbef3c","/zh/tag/pdfpreview/",{"y":"p","t":"PDFPreview 标签","I":0},["/zh/tag/pdfpreview/index.html"]],
  ["v-5b15e38a","/zh/category/proxy/",{"y":"p","t":"Proxy 分类","I":0},["/zh/category/proxy/index.html"]],
  ["v-c8a57284","/zh/tag/proxy/",{"y":"p","t":"Proxy 标签","I":0},["/zh/tag/proxy/index.html"]],
  ["v-2e2a7666","/zh/category/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/",{"y":"p","t":"设计模式 分类","I":0},["/zh/category/设计模式/","/zh/category/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/index.html"]],
  ["v-2598a69c","/zh/tag/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/",{"y":"p","t":"设计模式 标签","I":0},["/zh/tag/设计模式/","/zh/tag/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/index.html"]],
  ["v-cfd0904a","/zh/category/nodejs/",{"y":"p","t":"nodejs 分类","I":0},["/zh/category/nodejs/index.html"]],
  ["v-6a6cbb27","/zh/tag/nodejs/",{"y":"p","t":"nodejs 标签","I":0},["/zh/tag/nodejs/index.html"]],
  ["v-8faafe26","/zh/category/npm/",{"y":"p","t":"npm 分类","I":0},["/zh/category/npm/index.html"]],
  ["v-4ba63574","/zh/tag/-npm/",{"y":"p","t":"-npm 标签","I":0},["/zh/tag/-npm/index.html"]],
  ["v-8fa3949c","/zh/category/vue/",{"y":"p","t":"Vue 分类","I":0},["/zh/category/vue/index.html"]],
  ["v-6decd5e6","/zh/tag/vue/",{"y":"p","t":"Vue 标签","I":0},["/zh/tag/vue/index.html"]],
  ["v-4e127069","/zh/category/standard/",{"y":"p","t":"Standard 分类","I":0},["/zh/category/standard/index.html"]],
  ["v-41985e96","/zh/tag/standard/",{"y":"p","t":"Standard 标签","I":0},["/zh/tag/standard/index.html"]],
  ["v-7719c3dd","/zh/javascript/axios.html",{"a":"WY","d":"2023-03-22T00:00:00.000Z","l":"2023年3月22日","c":["javascript","Axios","Ajax","Fetch"],"g":["javascript","Axios","Ajax","Fetch"],"u":true,"y":"a","t":"Axios Ajax  Fetch","i":"page","O":1,"s":"Axios Ajax  Fetch"},["/zh/javascript/axios","/zh/javascript/axios.md"]],
]
