export const data = JSON.parse("{\"key\":\"v-0352acb8\",\"path\":\"/zh/vue/devStandard.html\",\"title\":\"开发规范-Vue\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"开发规范-Vue\",\"shortTitle\":\"开发规范\",\"icon\":\"page\",\"order\":1,\"author\":\"WY\",\"date\":\"2023-03-08T00:00:00.000Z\",\"category\":[\"Vue\",\"Standard\"],\"tag\":[\"Vue\",\"Standard\"],\"sticky\":true,\"star\":true,\"footer\":\"Footer content for test\",\"copyright\":\"No Copyright\",\"description\":\"命名规范\\rcamelCase (小驼峰式命名法 -- 首字母小写); \\rPascalCse (大驼峰式命名 --首字母大写); \\rkebad-case (短横线连接式); \\rSnake (下划线连接式); 项目文件命名\\r项目名; \\r全部采用小写方式，以短横线分割; \\r目录名; 参照项目命名规则，有复数结构时，要采用复数命名法。例：docs、assets...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://wangyongtest.github.io/frontendtechnologysharing.github.com/zh/vue/devStandard.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"开发规范-Vue\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"命名规范\\rcamelCase (小驼峰式命名法 -- 首字母小写); \\rPascalCse (大驼峰式命名 --首字母大写); \\rkebad-case (短横线连接式); \\rSnake (下划线连接式); 项目文件命名\\r项目名; \\r全部采用小写方式，以短横线分割; \\r目录名; 参照项目命名规则，有复数结构时，要采用复数命名法。例：docs、assets...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"WY\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Vue\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Standard\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-03-08T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"开发规范-Vue\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-03-08T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"WY\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"命名规范\",\"slug\":\"命名规范\",\"link\":\"#命名规范\",\"children\":[{\"level\":3,\"title\":\"项目文件命名\",\"slug\":\"项目文件命名\",\"link\":\"#项目文件命名\",\"children\":[]},{\"level\":3,\"title\":\"Vue 组件命名\",\"slug\":\"vue-组件命名\",\"link\":\"#vue-组件命名\",\"children\":[]},{\"level\":3,\"title\":\"代码参数命名\",\"slug\":\"代码参数命名\",\"link\":\"#代码参数命名\",\"children\":[]},{\"level\":3,\"title\":\"代码规范\",\"slug\":\"代码规范\",\"link\":\"#代码规范\",\"children\":[]},{\"level\":3,\"title\":\"HTML\",\"slug\":\"html\",\"link\":\"#html\",\"children\":[]},{\"level\":3,\"title\":\"CSS\",\"slug\":\"css\",\"link\":\"#css\",\"children\":[]},{\"level\":3,\"title\":\"Javascript\",\"slug\":\"javascript\",\"link\":\"#javascript\",\"children\":[]},{\"level\":3,\"title\":\"注释规范\",\"slug\":\"注释规范\",\"link\":\"#注释规范\",\"children\":[]},{\"level\":3,\"title\":\"其他\",\"slug\":\"其他\",\"link\":\"#其他\",\"children\":[]}]}],\"readingTime\":{\"minutes\":20.85,\"words\":6255},\"filePathRelative\":\"zh/vue/devStandard.md\",\"localizedDate\":\"2023年3月8日\",\"excerpt\":\"\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
